/**
 * Error code definitions for ClaudeKit.
 * Organized by domain for easy reference.
 */

// General errors
export const ERR_UNKNOWN = 'ERR_UNKNOWN';
export const ERR_INVALID_INPUT = 'ERR_INVALID_INPUT';
export const ERR_NOT_FOUND = 'ERR_NOT_FOUND';
export const ERR_PERMISSION_DENIED = 'ERR_PERMISSION_DENIED';
export const ERR_TIMEOUT = 'ERR_TIMEOUT';

// File system errors
export const ERR_FILE_NOT_FOUND = 'ERR_FILE_NOT_FOUND';
export const ERR_FILE_READ_FAILED = 'ERR_FILE_READ_FAILED';
export const ERR_FILE_WRITE_FAILED = 'ERR_FILE_WRITE_FAILED';
export const ERR_DIRECTORY_NOT_FOUND = 'ERR_DIRECTORY_NOT_FOUND';
export const ERR_DIRECTORY_CREATE_FAILED = 'ERR_DIRECTORY_CREATE_FAILED';
export const ERR_INVALID_PATH = 'ERR_INVALID_PATH';

// Git errors
export const ERR_GIT_NOT_FOUND = 'ERR_GIT_NOT_FOUND';
export const ERR_GIT_NOT_INITIALIZED = 'ERR_GIT_NOT_INITIALIZED';
export const ERR_GIT_COMMAND_FAILED = 'ERR_GIT_COMMAND_FAILED';
export const ERR_GIT_NO_CHANGES = 'ERR_GIT_NO_CHANGES';
export const ERR_GIT_CONFLICT = 'ERR_GIT_CONFLICT';
export const ERR_GIT_PROTECTED_BRANCH = 'ERR_GIT_PROTECTED_BRANCH';
export const ERR_GIT_REMOTE_NOT_FOUND = 'ERR_GIT_REMOTE_NOT_FOUND';
export const ERR_GH_CLI_NOT_FOUND = 'ERR_GH_CLI_NOT_FOUND';

// Kit/Installation errors
export const ERR_KIT_NOT_FOUND = 'ERR_KIT_NOT_FOUND';
export const ERR_KIT_INVALID = 'ERR_KIT_INVALID';
export const ERR_ALREADY_INITIALIZED = 'ERR_ALREADY_INITIALIZED';
export const ERR_NOT_INITIALIZED = 'ERR_NOT_INITIALIZED';
export const ERR_VERSION_MISMATCH = 'ERR_VERSION_MISMATCH';
export const ERR_UPDATE_FAILED = 'ERR_UPDATE_FAILED';
export const ERR_ROLLBACK_FAILED = 'ERR_ROLLBACK_FAILED';

// Configuration errors
export const ERR_CONFIG_INVALID = 'ERR_CONFIG_INVALID';
export const ERR_CONFIG_SCHEMA_VIOLATION = 'ERR_CONFIG_SCHEMA_VIOLATION';
export const ERR_CONFIG_MIGRATION_FAILED = 'ERR_CONFIG_MIGRATION_FAILED';

// Command errors
export const ERR_COMMAND_NOT_FOUND = 'ERR_COMMAND_NOT_FOUND';
export const ERR_COMMAND_INVALID = 'ERR_COMMAND_INVALID';
export const ERR_COMMAND_EXECUTION_FAILED = 'ERR_COMMAND_EXECUTION_FAILED';

// Network/API errors
export const ERR_NETWORK_ERROR = 'ERR_NETWORK_ERROR';
export const ERR_API_ERROR = 'ERR_API_ERROR';
export const ERR_RATE_LIMITED = 'ERR_RATE_LIMITED';

// Agent/Service errors
export const ERR_AGENT_NOT_FOUND = 'ERR_AGENT_NOT_FOUND';
export const ERR_AGENT_SPAWN_FAILED = 'ERR_AGENT_SPAWN_FAILED';
export const ERR_SKILL_NOT_FOUND = 'ERR_SKILL_NOT_FOUND';
export const ERR_SKILL_ACTIVATION_FAILED = 'ERR_SKILL_ACTIVATION_FAILED';
